'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Abo_Abonos
    Public Property ID As Integer
    Public Property Abo_Fecha As Date
    Public Property Cre_ID_Credito As Integer

    Public Overridable Property Cre_Creditos As Cre_Creditos

End Class
