'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class BD_CPCEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BD_CPCEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Abo_Abonos() As DbSet(Of Abo_Abonos)
    Public Overridable Property Cli_Clientes() As DbSet(Of Cli_Clientes)
    Public Overridable Property Cra_Creditos_Atrasados() As DbSet(Of Cra_Creditos_Atrasados)
    Public Overridable Property Cre_Creditos() As DbSet(Of Cre_Creditos)
    Public Overridable Property Tip_Tipos_Usuarios() As DbSet(Of Tip_Tipos_Usuarios)
    Public Overridable Property Usu_Usuarios() As DbSet(Of Usu_Usuarios)

    Public Overridable Function actualizarCredito(iD_Credito As Nullable(Of Integer), nuevo_Monto_Pendiente As Nullable(Of Decimal)) As Integer
        Dim iD_CreditoParameter As ObjectParameter = If(iD_Credito.HasValue, New ObjectParameter("ID_Credito", iD_Credito), New ObjectParameter("ID_Credito", GetType(Integer)))

        Dim nuevo_Monto_PendienteParameter As ObjectParameter = If(nuevo_Monto_Pendiente.HasValue, New ObjectParameter("Nuevo_Monto_Pendiente", nuevo_Monto_Pendiente), New ObjectParameter("Nuevo_Monto_Pendiente", GetType(Decimal)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("actualizarCredito", iD_CreditoParameter, nuevo_Monto_PendienteParameter)
    End Function

    Public Overridable Function actualizarSaldoCrediticio(iD_Cliente As Nullable(Of Integer), nuevo_Saldo As Nullable(Of Decimal)) As Integer
        Dim iD_ClienteParameter As ObjectParameter = If(iD_Cliente.HasValue, New ObjectParameter("ID_Cliente", iD_Cliente), New ObjectParameter("ID_Cliente", GetType(Integer)))

        Dim nuevo_SaldoParameter As ObjectParameter = If(nuevo_Saldo.HasValue, New ObjectParameter("Nuevo_Saldo", nuevo_Saldo), New ObjectParameter("Nuevo_Saldo", GetType(Decimal)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("actualizarSaldoCrediticio", iD_ClienteParameter, nuevo_SaldoParameter)
    End Function

    Public Overridable Function muestraAbonos() As ObjectResult(Of muestraAbonos_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of muestraAbonos_Result)("muestraAbonos")
    End Function

    Public Overridable Function muestraClientes() As ObjectResult(Of muestraClientes_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of muestraClientes_Result)("muestraClientes")
    End Function

    Public Overridable Function muestraCreditos() As ObjectResult(Of muestraCreditos_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of muestraCreditos_Result)("muestraCreditos")
    End Function

    Public Overridable Function muestraUsuarios() As ObjectResult(Of muestraUsuarios_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of muestraUsuarios_Result)("muestraUsuarios")
    End Function

End Class
