'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cra_Creditos_Atrasados
    Public Property ID As Integer
    Public Property Cra_Meses_Atrasados As Integer
    Public Property Cra_Intereses As Decimal
    Public Property Cre_ID_Credito As Integer

    Public Overridable Property Cre_Creditos As Cre_Creditos

End Class
