'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cre_Creditos
    Public Property ID As Integer
    Public Property Cre_Monto_Total As Decimal
    Public Property Cre_Monto_Pendiente As Decimal
    Public Property Cre_Cuotas As Decimal
    Public Property Cre_Plazo As Integer
    Public Property Cre_Fecha_Inicial As Date
    Public Property Usu_ID_Usuario As Integer
    Public Property Cli_ID_Cliente As Integer

    Public Overridable Property Abo_Abonos As ICollection(Of Abo_Abonos) = New HashSet(Of Abo_Abonos)
    Public Overridable Property Cli_Clientes As Cli_Clientes
    Public Overridable Property Cra_Creditos_Atrasados As ICollection(Of Cra_Creditos_Atrasados) = New HashSet(Of Cra_Creditos_Atrasados)
    Public Overridable Property Usu_Usuarios As Usu_Usuarios

End Class
