'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tip_Tipos_Usuarios
    Public Property ID As Integer
    Public Property Tip_Puesto As String

    Public Overridable Property Usu_Usuarios As ICollection(Of Usu_Usuarios) = New HashSet(Of Usu_Usuarios)

End Class
