'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usu_Usuarios
    Public Property ID As Integer
    Public Property Usu_Nombre As String
    Public Property Usu_Primer_Apellido As String
    Public Property Usu_Segundo_Apellido As String
    Public Property Usu_Nick As String
    Public Property Usu_Contraseña As String
    Public Property Tip_ID_Tipo_Usuario As Integer

    Public Overridable Property Cre_Creditos As ICollection(Of Cre_Creditos) = New HashSet(Of Cre_Creditos)
    Public Overridable Property Tip_Tipos_Usuarios As Tip_Tipos_Usuarios

End Class
